-- Esquema de operaciones de Casa Gracia (Postgres / Neon).
-- Idempotente: aplicar con `npm run migrate`.
--
-- Modelo de acceso: cada persona tiene un rol (empleado < lider < jefe < admin) y,
-- si es empleado o lider, un área (limpieza, mantenimiento, recepcion, ...). El área
-- delimita qué ve y qué puede tocar; el rol delimita qué puede hacer dentro de ella.

CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  name text NOT NULL,
  role text NOT NULL CHECK (role IN ('empleado','lider','jefe','admin')),
  area text CHECK (area IN ('limpieza','mantenimiento','recepcion','cocina','lavanderia','administracion')),
  active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS rooms (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  floor text NOT NULL,
  type text NOT NULL CHECK (type IN ('privada','suite','compartida','zona_comun')),
  status text NOT NULL DEFAULT 'sucia'
    CHECK (status IN ('sucia','en_limpieza','pendiente_inspeccion','lista','bloqueada')),
  notes text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS checklist_templates (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_type text NOT NULL,
  task_type text NOT NULL,
  UNIQUE (room_type, task_type)
);

-- requires_evidence: el punto no se puede marcar hecho sin adjuntar evidencia.
-- evidence_kind: 'foto' | 'video' | 'cualquiera'.
CREATE TABLE IF NOT EXISTS checklist_template_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id integer NOT NULL REFERENCES checklist_templates(id) ON DELETE CASCADE,
  text text NOT NULL,
  position integer NOT NULL,
  requires_evidence boolean NOT NULL DEFAULT false,
  evidence_kind text NOT NULL DEFAULT 'cualquiera' CHECK (evidence_kind IN ('foto','video','cualquiera')),
  min_evidence integer NOT NULL DEFAULT 1 CHECK (min_evidence >= 1)
);

CREATE TABLE IF NOT EXISTS incidents (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id integer NOT NULL REFERENCES rooms(id),
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  priority text NOT NULL DEFAULT 'media' CHECK (priority IN ('baja','media','alta','urgente')),
  status text NOT NULL DEFAULT 'abierta' CHECK (status IN ('abierta','en_curso','resuelta')),
  blocks_room boolean NOT NULL DEFAULT false,
  photo text,
  area text NOT NULL DEFAULT 'mantenimiento',
  reported_by integer NOT NULL REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz
);

-- area: el equipo dueño del trabajo (gobierna visibilidad y permisos).
-- type: la clase de trabajo (gobierna la checklist y el estado derivado de la habitación).
CREATE TABLE IF NOT EXISTS tasks (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id integer NOT NULL REFERENCES rooms(id),
  area text NOT NULL DEFAULT 'limpieza'
    CHECK (area IN ('limpieza','mantenimiento','recepcion','cocina','lavanderia','administracion')),
  type text NOT NULL
    CHECK (type IN ('limpieza','mantenimiento','inspeccion','recepcion','cocina','lavanderia','general')),
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  priority text NOT NULL DEFAULT 'media' CHECK (priority IN ('baja','media','alta','urgente')),
  status text NOT NULL DEFAULT 'pendiente'
    CHECK (status IN ('pendiente','en_curso','hecha','verificada','rechazada','cancelada')),
  assignee_id integer REFERENCES users(id),
  incident_id integer REFERENCES incidents(id),
  created_by integer NOT NULL REFERENCES users(id),
  reviewed_by integer REFERENCES users(id),
  review_note text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  started_at timestamptz,
  done_at timestamptz,
  verified_at timestamptz,
  rejected_at timestamptz
);

CREATE TABLE IF NOT EXISTS task_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id integer NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  text text NOT NULL,
  done boolean NOT NULL DEFAULT false,
  position integer NOT NULL,
  requires_evidence boolean NOT NULL DEFAULT false,
  evidence_kind text NOT NULL DEFAULT 'cualquiera' CHECK (evidence_kind IN ('foto','video','cualquiera')),
  min_evidence integer NOT NULL DEFAULT 1 CHECK (min_evidence >= 1)
);

-- Evidencia fotográfica / de vídeo. Los bytes viven en el object storage (Supabase);
-- aquí solo queda el puntero y la trazabilidad (quién, cuándo, para qué punto).
CREATE TABLE IF NOT EXISTS evidence (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id integer REFERENCES tasks(id) ON DELETE CASCADE,
  task_item_id integer REFERENCES task_items(id) ON DELETE CASCADE,
  incident_id integer REFERENCES incidents(id) ON DELETE CASCADE,
  kind text NOT NULL CHECK (kind IN ('foto','video')),
  storage_path text NOT NULL UNIQUE,
  mime text NOT NULL DEFAULT '',
  size_bytes integer NOT NULL DEFAULT 0,
  duration_ms integer,
  uploaded_by integer NOT NULL REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (task_id IS NOT NULL OR incident_id IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS lost_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id integer REFERENCES rooms(id),
  description text NOT NULL,
  photo text,
  status text NOT NULL DEFAULT 'guardado' CHECK (status IN ('guardado','reclamado','entregado')),
  found_by integer NOT NULL REFERENCES users(id),
  claimant text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz
);

CREATE TABLE IF NOT EXISTS inventory_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  category text NOT NULL DEFAULT 'general',
  unit text NOT NULL DEFAULT 'ud',
  min_qty integer NOT NULL DEFAULT 0,
  qty integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS inventory_movements (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id integer NOT NULL REFERENCES inventory_items(id) ON DELETE CASCADE,
  delta integer NOT NULL,
  reason text NOT NULL DEFAULT '',
  user_id integer NOT NULL REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS messages (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id integer REFERENCES tasks(id) ON DELETE CASCADE,
  incident_id integer REFERENCES incidents(id) ON DELETE CASCADE,
  sender_id integer NOT NULL REFERENCES users(id),
  text text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS push_tokens (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id),
  token text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- --- Migración de bases anteriores al modelo de roles/áreas y evidencias -------
-- Todo lo de abajo es no-op en una base recién creada con las definiciones de arriba.
-- Los CHECK se recrean siempre (DROP IF EXISTS + ADD) para que el script sea reejecutable.

-- users: roles planos (admin/limpieza/mantenimiento) -> rol jerárquico + área.
ALTER TABLE users ADD COLUMN IF NOT EXISTS area text;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_area_check;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_area_required_check;

UPDATE users SET area = role WHERE role IN ('limpieza','mantenimiento') AND area IS NULL;
UPDATE users SET role = 'empleado' WHERE role IN ('limpieza','mantenimiento');

ALTER TABLE users ADD CONSTRAINT users_role_check
  CHECK (role IN ('empleado','lider','jefe','admin'));
ALTER TABLE users ADD CONSTRAINT users_area_check
  CHECK (area IS NULL OR area IN ('limpieza','mantenimiento','recepcion','cocina','lavanderia','administracion'));
-- Un empleado o un líder sin área no tendría nada que ver ni nadie a quien responder.
ALTER TABLE users ADD CONSTRAINT users_area_required_check
  CHECK (role NOT IN ('empleado','lider') OR area IS NOT NULL);

-- tasks: área dueña del trabajo, estado 'rechazada' y traza de revisión.
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS area text;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS reviewed_by integer REFERENCES users(id);
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS review_note text NOT NULL DEFAULT '';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS rejected_at timestamptz;
-- La inspección la ejecuta el equipo de limpieza (la verifica su líder).
UPDATE tasks SET area = CASE WHEN type = 'mantenimiento' THEN 'mantenimiento' ELSE 'limpieza' END
  WHERE area IS NULL;
ALTER TABLE tasks ALTER COLUMN area SET NOT NULL;
ALTER TABLE tasks ALTER COLUMN area SET DEFAULT 'limpieza';

ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_area_check;
ALTER TABLE tasks ADD CONSTRAINT tasks_area_check
  CHECK (area IN ('limpieza','mantenimiento','recepcion','cocina','lavanderia','administracion'));
ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_type_check;
ALTER TABLE tasks ADD CONSTRAINT tasks_type_check
  CHECK (type IN ('limpieza','mantenimiento','inspeccion','recepcion','cocina','lavanderia','general'));
ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_status_check;
ALTER TABLE tasks ADD CONSTRAINT tasks_status_check
  CHECK (status IN ('pendiente','en_curso','hecha','verificada','rechazada','cancelada'));

-- incidents: área a la que se deriva la avería (por defecto, mantenimiento).
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS area text NOT NULL DEFAULT 'mantenimiento';

-- Exigencia de evidencia en los puntos de checklist (plantilla y copia de la tarea).
ALTER TABLE checklist_template_items ADD COLUMN IF NOT EXISTS requires_evidence boolean NOT NULL DEFAULT false;
ALTER TABLE checklist_template_items ADD COLUMN IF NOT EXISTS evidence_kind text NOT NULL DEFAULT 'cualquiera';
ALTER TABLE checklist_template_items ADD COLUMN IF NOT EXISTS min_evidence integer NOT NULL DEFAULT 1;
ALTER TABLE task_items ADD COLUMN IF NOT EXISTS requires_evidence boolean NOT NULL DEFAULT false;
ALTER TABLE task_items ADD COLUMN IF NOT EXISTS evidence_kind text NOT NULL DEFAULT 'cualquiera';
ALTER TABLE task_items ADD COLUMN IF NOT EXISTS min_evidence integer NOT NULL DEFAULT 1;

CREATE INDEX IF NOT EXISTS idx_tasks_room ON tasks(room_id);
CREATE INDEX IF NOT EXISTS idx_tasks_assignee ON tasks(assignee_id);
CREATE INDEX IF NOT EXISTS idx_tasks_area ON tasks(area, status);
CREATE INDEX IF NOT EXISTS idx_incidents_room ON incidents(room_id);
CREATE INDEX IF NOT EXISTS idx_messages_task ON messages(task_id);
CREATE INDEX IF NOT EXISTS idx_messages_incident ON messages(incident_id);
CREATE INDEX IF NOT EXISTS idx_push_tokens_user ON push_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_evidence_task ON evidence(task_id);
CREATE INDEX IF NOT EXISTS idx_evidence_task_item ON evidence(task_item_id);
CREATE INDEX IF NOT EXISTS idx_evidence_incident ON evidence(incident_id);
