-- Esquema de operaciones de Casa Gracia (Postgres / Neon).
-- Idempotente: aplicar con `npm run migrate`.
--
-- Modelo de acceso: cada persona tiene un rol (empleado < jefe < admin) y,
-- si es empleado, un área (limpieza, mantenimiento, recepcion, ...). El área
-- delimita qué ve y qué puede tocar; el rol delimita qué puede hacer dentro de ella.

CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  name text NOT NULL,
  role text NOT NULL CHECK (role IN ('empleado','jefe','admin')),
  area text CHECK (area IN ('limpieza','mantenimiento','recepcion','cocina','lavanderia','administracion')),
  active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS rooms (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  floor text NOT NULL,
  type text NOT NULL CHECK (type IN ('privada','suite','compartida','zona_comun')),
  status text NOT NULL DEFAULT 'sucia'
    CHECK (status IN ('sucia','en_limpieza','pendiente_inspeccion','lista','ocupada','bloqueada')),
  notes text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS checklist_templates (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_type text NOT NULL,
  task_type text NOT NULL,
  UNIQUE (room_type, task_type)
);

-- requires_evidence: el punto no se puede marcar hecho sin adjuntar evidencia.
-- evidence_kind: 'foto' | 'video' | 'cualquiera'.
CREATE TABLE IF NOT EXISTS checklist_template_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id integer NOT NULL REFERENCES checklist_templates(id) ON DELETE CASCADE,
  text text NOT NULL,
  position integer NOT NULL,
  requires_evidence boolean NOT NULL DEFAULT false,
  evidence_kind text NOT NULL DEFAULT 'cualquiera' CHECK (evidence_kind IN ('foto','video','cualquiera')),
  min_evidence integer NOT NULL DEFAULT 1 CHECK (min_evidence >= 1)
);

-- La checklist PROPIA de cada habitación o zona, por tipo de trabajo. Es la que se
-- copia a la tarea al crearla: dos habitaciones del mismo tipo pueden exigir cosas
-- distintas (la 103 tiene ventana exterior; la piscina no se hace la cama).
-- `checklist_templates` queda como el juego de puntos POR DEFECTO de un tipo de
-- habitación: solo se usa para sembrar la checklist de una habitación que no tiene
-- la suya todavía (alta nueva o base recién migrada).
CREATE TABLE IF NOT EXISTS room_checklist_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id integer NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  task_type text NOT NULL
    CHECK (task_type IN ('limpieza','mantenimiento','inspeccion','recepcion','cocina','lavanderia','general')),
  text text NOT NULL,
  position integer NOT NULL,
  requires_evidence boolean NOT NULL DEFAULT false,
  evidence_kind text NOT NULL DEFAULT 'cualquiera' CHECK (evidence_kind IN ('foto','video','cualquiera')),
  min_evidence integer NOT NULL DEFAULT 1 CHECK (min_evidence >= 1)
);
CREATE INDEX IF NOT EXISTS idx_room_checklist ON room_checklist_items(room_id, task_type);

CREATE TABLE IF NOT EXISTS incidents (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id integer NOT NULL REFERENCES rooms(id),
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  priority text NOT NULL DEFAULT 'media' CHECK (priority IN ('baja','media','alta','urgente')),
  status text NOT NULL DEFAULT 'abierta' CHECK (status IN ('abierta','en_curso','resuelta')),
  blocks_room boolean NOT NULL DEFAULT false,
  photo text,
  area text NOT NULL DEFAULT 'mantenimiento',
  reported_by integer NOT NULL REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz
);

-- area: el equipo dueño del trabajo (gobierna visibilidad y permisos).
-- type: la clase de trabajo (gobierna la checklist y el estado derivado de la habitación).
CREATE TABLE IF NOT EXISTS tasks (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id integer NOT NULL REFERENCES rooms(id),
  area text NOT NULL DEFAULT 'limpieza'
    CHECK (area IN ('limpieza','mantenimiento','recepcion','cocina','lavanderia','administracion')),
  type text NOT NULL
    CHECK (type IN ('limpieza','mantenimiento','inspeccion','recepcion','cocina','lavanderia','general')),
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  priority text NOT NULL DEFAULT 'media' CHECK (priority IN ('baja','media','alta','urgente')),
  status text NOT NULL DEFAULT 'pendiente'
    CHECK (status IN ('pendiente','en_curso','hecha','verificada','rechazada','cancelada','vencida','impugnada')),
  assignee_id integer REFERENCES users(id),
  incident_id integer REFERENCES incidents(id),
  created_by integer NOT NULL REFERENCES users(id),
  reviewed_by integer REFERENCES users(id),
  review_note text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  started_at timestamptz,
  done_at timestamptz,
  verified_at timestamptz,
  rejected_at timestamptz,
  -- due_at: plazo automático según prioridad (ver TASK_SLA_HOURS). Superado sin
  -- completar, un barrido periódico pasa la tarea a 'vencida'.
  due_at timestamptz,
  expired_at timestamptz,
  -- disputed_at: se marcó 'verificada' pero el jefe encontró después que no se
  -- cumplió lo exigido (p.ej. evidencia insuficiente) y la impugna.
  disputed_at timestamptz
);

CREATE TABLE IF NOT EXISTS task_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id integer NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  text text NOT NULL,
  done boolean NOT NULL DEFAULT false,
  position integer NOT NULL,
  requires_evidence boolean NOT NULL DEFAULT false,
  evidence_kind text NOT NULL DEFAULT 'cualquiera' CHECK (evidence_kind IN ('foto','video','cualquiera')),
  min_evidence integer NOT NULL DEFAULT 1 CHECK (min_evidence >= 1)
);

-- Evidencia fotográfica / de vídeo. Los bytes viven en el object storage (Supabase);
-- aquí solo queda el puntero y la trazabilidad (quién, cuándo, para qué punto).
CREATE TABLE IF NOT EXISTS evidence (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id integer REFERENCES tasks(id) ON DELETE CASCADE,
  task_item_id integer REFERENCES task_items(id) ON DELETE CASCADE,
  incident_id integer REFERENCES incidents(id) ON DELETE CASCADE,
  kind text NOT NULL CHECK (kind IN ('foto','video')),
  storage_path text NOT NULL UNIQUE,
  mime text NOT NULL DEFAULT '',
  size_bytes integer NOT NULL DEFAULT 0,
  duration_ms integer,
  uploaded_by integer NOT NULL REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (task_id IS NOT NULL OR incident_id IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS lost_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id integer REFERENCES rooms(id),
  description text NOT NULL,
  photo text,
  status text NOT NULL DEFAULT 'guardado' CHECK (status IN ('guardado','reclamado','entregado')),
  found_by integer NOT NULL REFERENCES users(id),
  claimant text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz
);

CREATE TABLE IF NOT EXISTS inventory_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  category text NOT NULL DEFAULT 'general',
  unit text NOT NULL DEFAULT 'ud',
  min_qty integer NOT NULL DEFAULT 0,
  qty integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS inventory_movements (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id integer NOT NULL REFERENCES inventory_items(id) ON DELETE CASCADE,
  delta integer NOT NULL,
  reason text NOT NULL DEFAULT '',
  user_id integer NOT NULL REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS messages (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id integer REFERENCES tasks(id) ON DELETE CASCADE,
  incident_id integer REFERENCES incidents(id) ON DELETE CASCADE,
  sender_id integer NOT NULL REFERENCES users(id),
  text text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS push_tokens (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id),
  token text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Programaciones de tareas: recurrentes (diaria/semanal/mensual) y de una sola vez
-- con fecha ('una_vez'). El generador (runTaskSchedules, junto al barrido de plazo)
-- las materializa en tasks reales según las horas locales del hotel.
-- date_from ancla la recurrencia (día de la semana para 'semanal', día del mes para
-- 'mensual') y para 'una_vez' es el día de ejecución. date_to acota el periodo
-- (recurrente) o el plazo de la instancia (una_vez).
CREATE TABLE IF NOT EXISTS task_schedules (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id integer NOT NULL REFERENCES rooms(id),
  area text NOT NULL CHECK (area IN ('limpieza','mantenimiento','recepcion','cocina','lavanderia','administracion')),
  type text NOT NULL CHECK (type IN ('limpieza','mantenimiento','inspeccion','recepcion','cocina','lavanderia','general')),
  title text NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  priority text NOT NULL DEFAULT 'media' CHECK (priority IN ('baja','media','alta','urgente')),
  assignee_id integer REFERENCES users(id),
  freq text NOT NULL CHECK (freq IN ('una_vez','diaria','semanal','mensual')),
  run_hours integer[] NOT NULL DEFAULT '{8}',
  date_from date NOT NULL DEFAULT (now() AT TIME ZONE 'America/Bogota')::date,
  date_to date,
  active boolean NOT NULL DEFAULT true,
  created_by integer NOT NULL REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_task_schedules_active ON task_schedules(room_id) WHERE active;

-- Traza de qué programación y qué franja horaria exacta generó una instancia: es la
-- base de la idempotencia del generador (un slot no se materializa dos veces).
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS schedule_id integer REFERENCES task_schedules(id);
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS scheduled_slot timestamptz;
CREATE UNIQUE INDEX IF NOT EXISTS idx_tasks_schedule_slot
  ON tasks(schedule_id, scheduled_slot) WHERE schedule_id IS NOT NULL;

-- --- Migración de bases anteriores al modelo de roles/áreas y evidencias -------
-- Todo lo de abajo es no-op en una base recién creada con las definiciones de arriba.
-- Los CHECK se recrean siempre (DROP IF EXISTS + ADD) para que el script sea reejecutable.

-- users: roles planos (admin/limpieza/mantenimiento) -> rol jerárquico + área.
ALTER TABLE users ADD COLUMN IF NOT EXISTS area text;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_area_check;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_area_required_check;

UPDATE users SET area = role WHERE role IN ('limpieza','mantenimiento') AND area IS NULL;
UPDATE users SET role = 'empleado' WHERE role IN ('limpieza','mantenimiento');

-- Rol 'lider' retirado: pasa a empleado de su misma área (conserva el área, pierde
-- la potestad de crear/asignar/verificar del equipo, que ahora es solo del jefe).
UPDATE users SET role = 'empleado' WHERE role = 'lider';

ALTER TABLE users ADD CONSTRAINT users_role_check
  CHECK (role IN ('empleado','jefe','admin'));
ALTER TABLE users ADD CONSTRAINT users_area_check
  CHECK (area IS NULL OR area IN ('limpieza','mantenimiento','recepcion','cocina','lavanderia','administracion'));
-- Un empleado sin área no tendría nada que ver ni nadie a quien responder.
ALTER TABLE users ADD CONSTRAINT users_area_required_check
  CHECK (role != 'empleado' OR area IS NOT NULL);

-- tasks: área dueña del trabajo, estado 'rechazada' y traza de revisión.
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS area text;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS reviewed_by integer REFERENCES users(id);
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS review_note text NOT NULL DEFAULT '';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS rejected_at timestamptz;
-- La inspección la ejecuta el equipo de limpieza (la verifica el jefe).
UPDATE tasks SET area = CASE WHEN type = 'mantenimiento' THEN 'mantenimiento' ELSE 'limpieza' END
  WHERE area IS NULL;
ALTER TABLE tasks ALTER COLUMN area SET NOT NULL;
ALTER TABLE tasks ALTER COLUMN area SET DEFAULT 'limpieza';

ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_area_check;
ALTER TABLE tasks ADD CONSTRAINT tasks_area_check
  CHECK (area IN ('limpieza','mantenimiento','recepcion','cocina','lavanderia','administracion'));
ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_type_check;
ALTER TABLE tasks ADD CONSTRAINT tasks_type_check
  CHECK (type IN ('limpieza','mantenimiento','inspeccion','recepcion','cocina','lavanderia','general'));
ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_status_check;
ALTER TABLE tasks ADD CONSTRAINT tasks_status_check
  CHECK (status IN ('pendiente','en_curso','hecha','verificada','rechazada','cancelada','vencida','impugnada'));

-- tasks: plazo automático (vencida) e impugnación posterior a la verificación.
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS due_at timestamptz;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS expired_at timestamptz;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS disputed_at timestamptz;

-- incidents: área a la que se deriva la avería (por defecto, mantenimiento).
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS area text NOT NULL DEFAULT 'mantenimiento';

-- Exigencia de evidencia en los puntos de checklist (plantilla y copia de la tarea).
ALTER TABLE checklist_template_items ADD COLUMN IF NOT EXISTS requires_evidence boolean NOT NULL DEFAULT false;
ALTER TABLE checklist_template_items ADD COLUMN IF NOT EXISTS evidence_kind text NOT NULL DEFAULT 'cualquiera';
ALTER TABLE checklist_template_items ADD COLUMN IF NOT EXISTS min_evidence integer NOT NULL DEFAULT 1;
ALTER TABLE task_items ADD COLUMN IF NOT EXISTS requires_evidence boolean NOT NULL DEFAULT false;
ALTER TABLE task_items ADD COLUMN IF NOT EXISTS evidence_kind text NOT NULL DEFAULT 'cualquiera';
ALTER TABLE task_items ADD COLUMN IF NOT EXISTS min_evidence integer NOT NULL DEFAULT 1;

-- Bootstrap de la checklist por habitación: hasta ahora los puntos vivían solo por
-- TIPO de habitación. Cada habitación arranca con una copia de la plantilla de su
-- tipo y a partir de ahí lleva vida propia. Idempotente: solo siembra los pares
-- (habitación, tipo de trabajo) que aún no tienen ni un punto propio, así que no
-- pisa nunca una checklist ya editada a mano.
INSERT INTO room_checklist_items
  (room_id, task_type, text, position, requires_evidence, evidence_kind, min_evidence)
SELECT r.id, t.task_type, i.text, i.position, i.requires_evidence, i.evidence_kind, i.min_evidence
FROM rooms r
JOIN checklist_templates t ON t.room_type = r.type
JOIN checklist_template_items i ON i.template_id = t.id
WHERE NOT EXISTS (
  SELECT 1 FROM room_checklist_items c
  WHERE c.room_id = r.id AND c.task_type = t.task_type
);

CREATE INDEX IF NOT EXISTS idx_tasks_room ON tasks(room_id);
CREATE INDEX IF NOT EXISTS idx_tasks_assignee ON tasks(assignee_id);
CREATE INDEX IF NOT EXISTS idx_tasks_area ON tasks(area, status);
CREATE INDEX IF NOT EXISTS idx_tasks_due_at ON tasks(due_at) WHERE due_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_incidents_room ON incidents(room_id);
CREATE INDEX IF NOT EXISTS idx_messages_task ON messages(task_id);
CREATE INDEX IF NOT EXISTS idx_messages_incident ON messages(incident_id);
CREATE INDEX IF NOT EXISTS idx_push_tokens_user ON push_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_evidence_task ON evidence(task_id);
CREATE INDEX IF NOT EXISTS idx_evidence_task_item ON evidence(task_item_id);
CREATE INDEX IF NOT EXISTS idx_evidence_incident ON evidence(incident_id);

-- rooms: nuevo estado 'ocupada' (solo entra/sale por check-in/check-out, nunca por
-- el PATCH normal de estado). Recrea el CHECK para bases anteriores a esta columna.
ALTER TABLE rooms DROP CONSTRAINT IF EXISTS rooms_status_check;
ALTER TABLE rooms ADD CONSTRAINT rooms_status_check
  CHECK (status IN ('sucia','en_limpieza','pendiente_inspeccion','lista','ocupada','bloqueada'));

-- Estancias manuales (sin PMS): como mucho una activa por habitación a la vez.
CREATE TABLE IF NOT EXISTS room_stays (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id integer NOT NULL REFERENCES rooms(id),
  guest_name text NOT NULL DEFAULT '',
  notes text NOT NULL DEFAULT '',
  checkin_at timestamptz NOT NULL DEFAULT now(),
  expected_checkout date,
  checkout_at timestamptz,
  checked_in_by integer NOT NULL REFERENCES users(id),
  checked_out_by integer REFERENCES users(id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_room_stays_active
  ON room_stays(room_id) WHERE checkout_at IS NULL;

-- Historial append-only de tareas, incidencias y habitaciones. actor_id NULL = lo
-- hizo el sistema (barrido de vencimiento, generador de programaciones).
CREATE TABLE IF NOT EXISTS audit_log (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity text NOT NULL CHECK (entity IN ('task','incident','room')),
  entity_id integer NOT NULL,
  action text NOT NULL,
  from_value text,
  to_value text,
  note text NOT NULL DEFAULT '',
  actor_id integer REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_log(entity, entity_id, created_at);

-- Centro de notificaciones: persiste lo que hasta ahora solo salía por push (efímero,
-- se pierde si el dispositivo estaba offline o sin projectId de EAS configurado).
CREATE TABLE IF NOT EXISTS notifications (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type text NOT NULL,
  title text NOT NULL,
  body text NOT NULL DEFAULT '',
  ref_type text CHECK (ref_type IN ('task','incident','room')),
  ref_id integer,
  read_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id, read_at, created_at DESC);

-- Recurrencia semanal multi-día (L-X-V, etc). NULL conserva el comportamiento
-- anterior: un solo día, el de la semana de date_from. 0=domingo .. 6=sábado.
ALTER TABLE task_schedules ADD COLUMN IF NOT EXISTS week_days integer[];

-- Fin de turno: quien sale del hotel lo avisa desde su perfil y queda la hora exacta
-- de salida. Append-only, como audit_log: no se corrige, se vuelve a avisar.
CREATE TABLE IF NOT EXISTS shift_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id),
  ended_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_shift_logs_user ON shift_logs(user_id, ended_at DESC);

-- Entrada de turno: el mismo historial de shift_logs ahora también recibe el aviso
-- de llegada, no solo el de salida. 'salida' de default conserva las filas ya
-- existentes (todas eran de salida antes de este cambio).
ALTER TABLE shift_logs ADD COLUMN IF NOT EXISTS kind text NOT NULL DEFAULT 'salida';
ALTER TABLE shift_logs DROP CONSTRAINT IF EXISTS shift_logs_kind_check;
ALTER TABLE shift_logs ADD CONSTRAINT shift_logs_kind_check CHECK (kind IN ('entrada', 'salida'));

-- Nombre de quien de verdad hizo el trabajo: la tarea puede estar asignada a una
-- cuenta pero completada por otra persona del equipo (turnos compartidos). Obligatorio
-- al marcar la tarea como hecha, se valida en el PATCH de /api/tasks/:id.
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS done_by_name text;
